version: "3"
services:
        jobbot:
                build: . 
                ports:
                        - 3000:3000 
                environment: 
                        - "PORT=3000"
                        - "clientId="
                        - "clientSecret="
